// =============================================================================
// lib/pdf.ts — generate a downloadable monthly expense report (PDF) with jsPDF.
// Used by the monthly auto-reset and by the manual "download report" buttons.
// =============================================================================

import { jsPDF } from "jspdf";
import type { Category, Entry } from "./types";
import { formatMoney } from "./currency";

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
function monthTitle(key: string): string {
  const [y, m] = key.split("-");
  return `${MONTHS[Number(m) - 1] ?? m} ${y}`;
}

export function buildMonthlyPDF(
  month: string,
  entries: Entry[],
  categories: Category[],
  base: string
): jsPDF {
  const catMap: Record<string, Category> = Object.fromEntries(categories.map((c) => [c.id, c]));
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 40; // margin
  let y = 56;

  const expenses = entries.filter((e) => e.kind === "expense");
  const income = entries.filter((e) => e.kind !== "expense");
  const totalExp = expenses.reduce((s, e) => s + e.baseAmount, 0);
  const totalInc = income.reduce((s, e) => s + e.baseAmount, 0);

  // Header
  doc.setFontSize(22);
  doc.setTextColor(30, 30, 40);
  doc.text("Fiscal — Monthly Report", M, y);
  y += 22;
  doc.setFontSize(13);
  doc.setTextColor(110, 110, 130);
  doc.text(monthTitle(month), M, y);
  y += 26;

  // Summary box
  doc.setDrawColor(225);
  doc.setFillColor(245, 246, 250);
  doc.roundedRect(M, y, W - M * 2, 64, 6, 6, "FD");
  const col = (W - M * 2) / 3;
  const stat = (label: string, value: string, i: number, color: [number, number, number]) => {
    const x = M + 14 + col * i;
    doc.setFontSize(9); doc.setTextColor(120, 120, 140);
    doc.text(label.toUpperCase(), x, y + 22);
    doc.setFontSize(15); doc.setTextColor(...color);
    doc.text(value, x, y + 44);
  };
  stat("Income", formatMoney(totalInc, base as any), 0, [16, 150, 80]);
  stat("Expenses", formatMoney(totalExp, base as any), 1, [200, 60, 60]);
  stat("Net", formatMoney(totalInc - totalExp, base as any), 2, [40, 40, 60]);
  y += 64 + 26;

  // Category breakdown
  doc.setFontSize(13); doc.setTextColor(30, 30, 40);
  doc.text("By category", M, y); y += 16;
  const byCat = new Map<string, number>();
  for (const e of expenses) {
    const name = catMap[e.categoryId]?.name ?? "Uncategorized";
    byCat.set(name, (byCat.get(name) ?? 0) + e.baseAmount);
  }
  const cats = [...byCat.entries()].sort((a, b) => b[1] - a[1]);
  doc.setFontSize(10);
  if (cats.length === 0) {
    doc.setTextColor(150); doc.text("No expenses this month.", M, y + 14); y += 24;
  } else {
    for (const [name, amt] of cats) {
      const pct = totalExp ? Math.round((amt / totalExp) * 100) : 0;
      doc.setTextColor(60, 60, 75);
      doc.text(name, M, y + 13);
      doc.text(`${formatMoney(amt, base as any)}  (${pct}%)`, W - M, y + 13, { align: "right" });
      // bar
      doc.setFillColor(99, 102, 241);
      doc.rect(M, y + 18, (W - M * 2) * (pct / 100), 4, "F");
      y += 30;
      if (y > 740) { doc.addPage(); y = 56; }
    }
  }
  y += 12;

  // Transactions table
  if (y > 700) { doc.addPage(); y = 56; }
  doc.setFontSize(13); doc.setTextColor(30, 30, 40);
  doc.text(`Transactions (${entries.length})`, M, y); y += 18;
  doc.setFontSize(9); doc.setTextColor(120, 120, 140);
  doc.text("Date", M, y); doc.text("Category", M + 80, y);
  doc.text("Note", M + 190, y); doc.text("Amount", W - M, y, { align: "right" });
  y += 6; doc.setDrawColor(225); doc.line(M, y, W - M, y); y += 12;

  const sorted = [...entries].sort((a, b) => (a.date < b.date ? 1 : -1));
  doc.setFontSize(9);
  for (const e of sorted) {
    if (y > 800) { doc.addPage(); y = 56; }
    doc.setTextColor(120, 120, 140); doc.text(e.date, M, y);
    doc.setTextColor(60, 60, 75);
    doc.text((catMap[e.categoryId]?.name ?? "—").slice(0, 16), M + 80, y);
    doc.text((e.note || "").slice(0, 26), M + 190, y);
    const sign = e.kind === "expense" ? "-" : "+";
    if (e.kind !== "expense") doc.setTextColor(16, 150, 80);
    doc.text(`${sign}${formatMoney(e.baseAmount, base as any)}`, W - M, y, { align: "right" });
    y += 16;
  }

  // Footer
  doc.setFontSize(8); doc.setTextColor(170);
  doc.text("Generated by Fiscal", M, 820);

  return doc;
}

export function downloadMonthlyPDF(
  month: string,
  entries: Entry[],
  categories: Category[],
  base: string
): void {
  const doc = buildMonthlyPDF(month, entries, categories, base);
  doc.save(`fiscal-report-${month}.pdf`);
}
